# File: .github/workflows/refresh.yml
name: Refresh

on: workflow_dispatch

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.4
            
            
